// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/auth/login": {
            "post": {
                "description": "Inicia sesión en Supabase y devuelve un JWT si el usuario es un administrador",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "autenticacion"
                ],
                "summary": "Iniciar sesión como administrador",
                "parameters": [
                    {
                        "description": "Credenciales del administrador",
                        "name": "credenciales",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domain.LoginRequestDTO"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/domain.LoginResponseDTO"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/operativo/historial-servicios": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Devuelve todas las reservas del sistema incluyendo los nombres de cliente, servicio, fecha agendada, dirección y estado del servicio.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "operativo"
                ],
                "summary": "Obtiene el historial completo de servicios/reservas prestadas en la plataforma",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/domain.ReservaHistorialDTO"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/operativo/notificar-aceptacion": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Endpoint que simula o registra la notificación del prestador al cliente de que se aceptó la reserva. Por ahora retorna un mensaje exitoso de confirmación de notificación.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "operativo"
                ],
                "summary": "Informa al cliente que un prestador aceptó su reserva",
                "parameters": [
                    {
                        "description": "Datos de la reserva",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domain.NotificationRequestDTO"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/operativo/prestadores": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Devuelve la lista completa de prestadores de la base de datos, con nombre, correo, experiencia, calificación promedio y estado (disponible, ocupado, inactivo).",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "operativo"
                ],
                "summary": "Obtiene la lista de prestadores con su estado de disponibilidad en tiempo real",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/domain.PrestadorDetalladoDTO"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/reportes/actividad-usuarios": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Devuelve cuántos usuarios nuevos se registraron y cuántos usuarios activos (con al menos una reserva) hubo en el mes",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "reportes"
                ],
                "summary": "Obtiene la actividad de usuarios del mes",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Mes (1-12)",
                        "name": "mes",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Año (ej. 2026)",
                        "name": "anio",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/domain.ActividadUsuariosDTO"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/reportes/admin": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Devuelve el top de prestadores, cantidad de pqrs abiertas y estadísticas de reservas para un mes y año",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "reportes"
                ],
                "summary": "Obtiene un reporte consolidado para el administrador",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Mes (1-12)",
                        "name": "mes",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Año (ej. 2026)",
                        "name": "anio",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/domain.ReporteConsolidadoMensualDTO"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/reportes/admin/pdf": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Genera y devuelve un documento PDF con los datos de administrador, actividad y servicios",
                "produces": [
                    "application/pdf"
                ],
                "tags": [
                    "reportes"
                ],
                "summary": "Descarga el reporte general en PDF",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Mes (1-12)",
                        "name": "mes",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Año (ej. 2026)",
                        "name": "anio",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "reporte.pdf",
                        "schema": {
                            "type": "file"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/reportes/calificaciones": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Devuelve un listado completo con los comentarios, puntuaciones, fechas y nombres de los involucrados en cada reserva calificada.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "reportes"
                ],
                "summary": "Obtiene todas las calificaciones/reseñas de los servicios",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/domain.CalificacionDTO"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/reportes/servicios-populares": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Devuelve los 10 servicios con más reservas en el mes y año indicados, incluyendo nombre y categoría",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "reportes"
                ],
                "summary": "Obtiene los servicios más solicitados del mes",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Mes (1-12)",
                        "name": "mes",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Año (ej. 2026)",
                        "name": "anio",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/domain.ServicioPopularDTO"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/reservas/{id}/cancelar": {
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Permite a un cliente cancelar una de sus reservas siempre y cuando esté en estado pendiente o aceptada.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "reservas"
                ],
                "summary": "Cancela una reserva existente",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID de la Reserva",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Datos de cancelación (ID del Cliente)",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domain.CancelarReservaRequestDTO"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/domain.CancelarReservaResponseDTO"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "domain.ActividadUsuariosDTO": {
            "type": "object",
            "properties": {
                "anio": {
                    "type": "integer"
                },
                "mes": {
                    "type": "integer"
                },
                "usuarios_activos": {
                    "type": "integer"
                },
                "usuarios_nuevos": {
                    "type": "integer"
                }
            }
        },
        "domain.CalificacionDTO": {
            "type": "object",
            "properties": {
                "comentario": {
                    "type": "string"
                },
                "fecha_calificacion": {
                    "type": "string"
                },
                "id_calificacion": {
                    "type": "integer"
                },
                "id_reserva": {
                    "type": "integer"
                },
                "nombre_cliente": {
                    "description": "Datos extra para hacerlo más rico",
                    "type": "string"
                },
                "nombre_prestador": {
                    "type": "string"
                },
                "nombre_servicio": {
                    "type": "string"
                },
                "puntuacion": {
                    "type": "integer"
                }
            }
        },
        "domain.CancelarReservaRequestDTO": {
            "type": "object",
            "required": [
                "id_cliente"
            ],
            "properties": {
                "id_cliente": {
                    "type": "integer"
                }
            }
        },
        "domain.CancelarReservaResponseDTO": {
            "type": "object",
            "properties": {
                "estado_reserva": {
                    "type": "string"
                },
                "id_reserva": {
                    "type": "integer"
                },
                "mensaje": {
                    "type": "string"
                }
            }
        },
        "domain.LoginRequestDTO": {
            "type": "object",
            "required": [
                "correo",
                "password"
            ],
            "properties": {
                "correo": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                }
            }
        },
        "domain.LoginResponseDTO": {
            "type": "object",
            "properties": {
                "access_token": {
                    "type": "string"
                },
                "expires_in": {
                    "type": "integer"
                },
                "token_type": {
                    "type": "string"
                }
            }
        },
        "domain.NotificationRequestDTO": {
            "type": "object",
            "properties": {
                "estado_reserva": {
                    "type": "string"
                },
                "id_cliente": {
                    "type": "integer"
                },
                "id_prestador": {
                    "type": "integer"
                },
                "id_reserva": {
                    "type": "integer"
                }
            }
        },
        "domain.PrestadorDetalladoDTO": {
            "type": "object",
            "properties": {
                "apellido": {
                    "type": "string"
                },
                "calificacion_promedio": {
                    "type": "number"
                },
                "correo": {
                    "type": "string"
                },
                "estado_disponibilidad": {
                    "type": "string"
                },
                "experiencia": {
                    "type": "string"
                },
                "id_prestador": {
                    "type": "integer"
                },
                "nombre": {
                    "type": "string"
                }
            }
        },
        "domain.PrestadorTopDTO": {
            "type": "object",
            "properties": {
                "calificacion": {
                    "type": "number"
                },
                "correo_prestador": {
                    "type": "string"
                },
                "id_prestador": {
                    "type": "integer"
                },
                "nombre_prestador": {
                    "type": "string"
                },
                "total_servicios": {
                    "type": "integer"
                }
            }
        },
        "domain.ReporteConsolidadoMensualDTO": {
            "type": "object",
            "properties": {
                "anio": {
                    "type": "integer"
                },
                "mes": {
                    "type": "integer"
                },
                "pqrs_abiertas": {
                    "type": "integer"
                },
                "top_prestadores": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/domain.PrestadorTopDTO"
                    }
                },
                "total_aceptadas": {
                    "type": "integer"
                },
                "total_canceladas": {
                    "type": "integer"
                },
                "total_completadas": {
                    "type": "integer"
                },
                "total_pendientes": {
                    "type": "integer"
                },
                "total_reservas": {
                    "type": "integer"
                }
            }
        },
        "domain.ReservaHistorialDTO": {
            "type": "object",
            "properties": {
                "descripcion": {
                    "type": "string"
                },
                "direccion": {
                    "type": "string"
                },
                "estado_reserva": {
                    "type": "string"
                },
                "fecha_agenda": {
                    "type": "string"
                },
                "id_cliente": {
                    "type": "integer"
                },
                "id_prestador": {
                    "type": "integer"
                },
                "id_reserva": {
                    "type": "integer"
                },
                "id_servicio": {
                    "type": "integer"
                },
                "nombre_cliente": {
                    "type": "string"
                },
                "nombre_prestador": {
                    "type": "string"
                },
                "nombre_servicio": {
                    "type": "string"
                }
            }
        },
        "domain.ServicioPopularDTO": {
            "type": "object",
            "properties": {
                "categoria": {
                    "type": "string"
                },
                "id_servicio": {
                    "type": "integer"
                },
                "nombre_servicio": {
                    "type": "string"
                },
                "veces_solicitado": {
                    "type": "integer"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "2.0",
	Host:             "localhost:8080",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "API REST ServiYa (Reportes)",
	Description:      "API de Reportes generada con Onion Architecture, Unit of Work y Repository Pattern",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
